### ISSUE TITLE
Client not working with v2.2.1-merlot

### ISSUE THREAD

**Issue by Legion2** [OpenTOSCA/container-client#15] opened 2019-07-05 10:56 UTC
The current version (e84cf76a83e2f0470f0d7e78adf2b405cf0f5aea) of the container-client does not work with the new OpenTOSCA version v2.2.1-merlot.
When trying to provision an Application a 500 Server error is returned.
```
Problem accessing /csars/Some-Service_w1.csar/servicetemplates/%257Bhttp%253A%252F%252Fexample.com%252Ftosca%252Fservicetemplates%257DSome-Service_w1/buildplans/Some-Service_w1_buildPlan/instances
```

**Comment by ghareeb-falazi** [comment] 2019-07-22 14:34
Most likely, it is an issue with the container, which should be fixed by: 
https://github.com/OpenTOSCA/container/pull/108

When this is merged into master, can you try again?

**Comment by miwurster** [comment] 2019-07-22 15:33
PR OpenTOSCA/container#108 has been merged

**Comment by Legion2** [comment] 2019-07-22 17:08
The dockerhub build failed, because GitHub was down.

**Comment by wederbn** [comment] 2019-07-22 17:49
I triggered a rebuild, so it should work now

**Comment by Legion2** [comment] 2019-07-22 20:08
Client log:
```
22:02:29.497 [pool-1-thread-1] WARN  o.o.c.c.impl.SwaggerContainerClient - Timeout reached, plan has net been finished yet
22:02:29.501 [pool-1-thread-1] ERROR o.o.c.c.impl.SwaggerContainerClient - Error executing request
java.lang.RuntimeException: Could not determine plan instance
	at org.opentosca.container.client.impl.SwaggerContainerClient.lambda$provisionApplicationAsync$5(SwaggerContainerClient.java:208)
```
Container UI:
No instance created
Conainer log:
many NullPointerExceptions

**Comment by ghareeb-falazi** [comment] 2019-07-23 06:51
@Legion2 I am not able to reproduce the error. My setup is as follows: Docker images in the latest version (docker-compose files attached) and container-client that uses the latest `master` branch and that runs the test cases in `ContainerClientTests` class using the latest `MyTinyToDo_Bare_Docker.csar`

[opentosca-docker.zip](https://github.com/OpenTOSCA/container-client/files/3420590/opentosca-docker.zip)

**Closed as completed** 2019-07-23 07:27 UTC

**Comment by Legion2** [comment] 2019-07-23 08:16
Ok, my problem seems to be that BuildPlan is not generated for my uploaded CSARs.
